Do not report error on device dsconnected
Since commit 063a8339ed27b94a8fe1e53a284507eb2d044e15, a device
disconnection (when the adb connection is closed) makes the read() on
the "receiver" socket fail.

As a consequence, it reports:

    ERROR: Controller error

instead of:

    WARN: Device disconnected

To fix the issue, report a device disconnection in that case.