Use OpenGL for camera to adapt to the target size
The camera stream can only be rendered on a surface matching the input
size. If the video constraints change the size, an intermediate OpenGL
filter is required.

For example, since 1080 is not a multiple of 16, running scrcpy as
follows:

    scrcpy --video-source=camera --camera-size=1920x1080 \
           --min-size-alignment=16

resulted in:

    ERROR: Camera configuration error

An intermediate OpenGL filter allows adapting the size without error.